-- ##########################################################################
-- ## CREACIÓN DE TABLAS, PK, FK Y OBJETOS (DENTRO DEL ESQUEMA EXISTENTE)  ##
-- ## RECUERDA: CONECTAR COMO ESQUEMA_TURISMO                              ##
-- ##########################################################################


alter session set "_ORACLE_SCRIPT"=true;


create user turismo identified by 123456;
 
grant all privileges to turismo;

-- 1. Eliminación de Tablas (para asegurar una re-ejecución limpia)
-- Se eliminan en orden inverso por las dependencias de claves foráneas (FK).
DROP TABLE Turista_Vuelo CASCADE CONSTRAINTS;
DROP TABLE Categoria_Plaza_Ocupada CASCADE CONSTRAINTS;
DROP TABLE Vuelo CASCADE CONSTRAINTS;
DROP TABLE Turista_Hotel CASCADE CONSTRAINTS;
DROP TABLE Hotel CASCADE CONSTRAINTS;
DROP TABLE Turista_Sucursal CASCADE CONSTRAINTS;
DROP TABLE Sucursal CASCADE CONSTRAINTS;
DROP TABLE Telefono CASCADE CONSTRAINTS;
DROP TABLE Correo CASCADE CONSTRAINTS;
DROP TABLE Turista CASCADE CONSTRAINTS;
DROP TABLE Bitacora CASCADE CONSTRAINTS;
DROP TABLE Flag_Bitacora CASCADE CONSTRAINTS;
DROP TABLE Avion CASCADE CONSTRAINTS;
DROP TABLE Categoria_Plaza CASCADE CONSTRAINTS;

---
--- CREACIÓN DE ENTIDADES PRINCIPALES Y CATÁLOGOS
---

-- 1. Tabla Turista
CREATE TABLE Turista (
    id_turista NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre1 VARCHAR2(50) NOT NULL,
    nombre2 VARCHAR2(50),
    nombre3 VARCHAR2(50),
    apellido1 VARCHAR2(50) NOT NULL,
    apellido2 VARCHAR2(50),
    direccion VARCHAR2(255),
    CONSTRAINT pk_turista PRIMARY KEY (id_turista)
);

-- 2. Tabla Correo (Información de Contacto)
CREATE TABLE Correo (
    id_correo NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_turista NUMBER NOT NULL,
    tipo_correo VARCHAR2(50),
    correo VARCHAR2(100) NOT NULL UNIQUE,
    CONSTRAINT pk_correo PRIMARY KEY (id_correo)
);

-- 3. Tabla Telefono (Información de Contacto)
CREATE TABLE Telefono (
    id_telefono NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_turista NUMBER NOT NULL,
    tipo_telefono VARCHAR2(50),
    telefono VARCHAR2(20) NOT NULL,
    CONSTRAINT pk_telefono PRIMARY KEY (id_telefono)
);

-- 4. Tabla Sucursal
CREATE TABLE Sucursal (
    id_sucursal NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    direccion VARCHAR2(255),
    telefono VARCHAR2(20),
    ciudad VARCHAR2(100),
    CONSTRAINT pk_sucursal PRIMARY KEY (id_sucursal)
);

-- 5. Tabla Hotel
CREATE TABLE Hotel (
    id_hotel NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre VARCHAR2(100) NOT NULL,
    direccion VARCHAR2(255),
    ciudad VARCHAR2(100),
    telefono VARCHAR2(20),
    no_plaza_total NUMBER,
    no_plaza_ocupada NUMBER,
    CONSTRAINT pk_hotel PRIMARY KEY (id_hotel)
);

-- 6. Tabla Avion (Catálogo)
CREATE TABLE Avion (
    id_avion NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    tipo_avion VARCHAR2(100) NOT NULL UNIQUE,
    CONSTRAINT pk_avion PRIMARY KEY (id_avion)
);

-- 7. Tabla Vuelo
CREATE TABLE Vuelo (
    id_vuelo NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_avion NUMBER NOT NULL,
    fecha_hora TIMESTAMP NOT NULL,
    origen VARCHAR2(100) NOT NULL,
    destino VARCHAR2(100) NOT NULL,
    CONSTRAINT pk_vuelo PRIMARY KEY (id_vuelo)
);

-- 8. Tabla Categoria_Plaza (Catálogo)
CREATE TABLE Categoria_Plaza (
    id_categoria NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre VARCHAR2(50) NOT NULL UNIQUE,
    cantidad_plaza NUMBER NOT NULL,
    CONSTRAINT pk_categoria_plaza PRIMARY KEY (id_categoria)
);

-- 9. Tabla Categoria_Plaza_Ocupada (Detalle de Asiento)
CREATE TABLE Categoria_Plaza_Ocupada (
    id_categoria_plaza_ocupada NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_categoria NUMBER NOT NULL,
    codigo_asiento VARCHAR2(10) NOT NULL UNIQUE,
    CONSTRAINT pk_categoria_plaza_ocupada PRIMARY KEY (id_categoria_plaza_ocupada)
);

-- 10. Tabla Flag_Bitacora (Catálogo de Acciones)
CREATE TABLE Flag_Bitacora (
    id_flag NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre_flag VARCHAR2(100) NOT NULL UNIQUE,
    CONSTRAINT pk_flag_bitacora PRIMARY KEY (id_flag)
);

-- 11. Tabla Bitacora (Auditoría)
CREATE TABLE Bitacora (
    id_bitacora NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    fecha TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    campo_modificado VARCHAR2(100),
    valor_anterior VARCHAR2(255),
    valor_actual VARCHAR2(255),
    tipo_accion VARCHAR2(50) NOT NULL, -- INSERT, UPDATE, DELETE
    nombre_tabla_modificada VARCHAR2(100) NOT NULL,
    id_flag_bitacora NUMBER,
    CONSTRAINT pk_bitacora PRIMARY KEY (id_bitacora)
);

---
--- CREACIÓN DE TABLAS DE UNIÓN (RELACIONES N:M)
---

-- 12. Tabla Turista_Sucursal (Turista:Sucursal N:M)
CREATE TABLE Turista_Sucursal (
    id_turista NUMBER NOT NULL,
    id_sucursal NUMBER NOT NULL,
    CONSTRAINT pk_turista_sucursal PRIMARY KEY (id_turista, id_sucursal)
);

-- 13. Tabla Turista_Hotel (Turista:Hotel N:M)
CREATE TABLE Turista_Hotel (
    id_turista NUMBER NOT NULL,
    id_hotel NUMBER NOT NULL,
    regimen VARCHAR2(50),
    fecha_llegada DATE,
    fecha_salida DATE,
    CONSTRAINT pk_turista_hotel PRIMARY KEY (id_turista, id_hotel)
);

-- 14. Tabla Turista_Vuelo (Turista:Vuelo N:M)
CREATE TABLE Turista_Vuelo (
    id_turista NUMBER NOT NULL,
    id_vuelo NUMBER NOT NULL,
    id_categoria_plaza_ocupada NUMBER NOT NULL UNIQUE,
    CONSTRAINT pk_turista_vuelo PRIMARY KEY (id_turista, id_vuelo)
);

---
--- AÑADIR CLAVES FORÁNEAS (FK)
---

-- Turista - Correo - Telefono
ALTER TABLE Correo ADD CONSTRAINT fk_correo_turista FOREIGN KEY (id_turista) REFERENCES Turista (id_turista);
ALTER TABLE Telefono ADD CONSTRAINT fk_telefono_turista FOREIGN KEY (id_turista) REFERENCES Turista (id_turista);

-- Vuelo - Avion
ALTER TABLE Vuelo ADD CONSTRAINT fk_vuelo_avion FOREIGN KEY (id_avion) REFERENCES Avion (id_avion);

-- Categoria_Plaza_Ocupada
ALTER TABLE Categoria_Plaza_Ocupada ADD CONSTRAINT fk_cpo_categoria FOREIGN KEY (id_categoria) REFERENCES Categoria_Plaza (id_categoria);

-- Bitacora
ALTER TABLE Bitacora ADD CONSTRAINT fk_bitacora_flag FOREIGN KEY (id_flag_bitacora) REFERENCES Flag_Bitacora (id_flag);

-- Tablas de Unión: Turista_Sucursal
ALTER TABLE Turista_Sucursal ADD CONSTRAINT fk_ts_turista FOREIGN KEY (id_turista) REFERENCES Turista (id_turista);
ALTER TABLE Turista_Sucursal ADD CONSTRAINT fk_ts_sucursal FOREIGN KEY (id_sucursal) REFERENCES Sucursal (id_sucursal);

-- Tablas de Unión: Turista_Hotel
ALTER TABLE Turista_Hotel ADD CONSTRAINT fk_th_turista FOREIGN KEY (id_turista) REFERENCES Turista (id_turista);
ALTER TABLE Turista_Hotel ADD CONSTRAINT fk_th_hotel FOREIGN KEY (id_hotel) REFERENCES Hotel (id_hotel);

-- Tablas de Unión: Turista_Vuelo
ALTER TABLE Turista_Vuelo ADD CONSTRAINT fk_tv_turista FOREIGN KEY (id_turista) REFERENCES Turista (id_turista);
ALTER TABLE Turista_Vuelo ADD CONSTRAINT fk_tv_vuelo FOREIGN KEY (id_vuelo) REFERENCES Vuelo (id_vuelo);
ALTER TABLE Turista_Vuelo ADD CONSTRAINT fk_tv_cpo FOREIGN KEY (id_categoria_plaza_ocupada) REFERENCES Categoria_Plaza_Ocupada (id_categoria_plaza_ocupada);

---
--- INSERCIÓN DE DATOS INICIALES PARA CATÁLOGOS
---

INSERT INTO Flag_Bitacora (nombre_flag) VALUES ('CREACION_REGISTRO');
INSERT INTO Flag_Bitacora (nombre_flag) VALUES ('ACTUALIZACION_REGISTRO');
INSERT INTO Flag_Bitacora (nombre_flag) VALUES ('ELIMINACION_REGISTRO');

COMMIT;

SELECT 'Script de tablas del esquema ejecutado exitosamente.' AS Mensaje FROM DUAL;
